# Generated by Django 3.0.2 on 2020-02-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200218_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='job_title',
            new_name='job',
        ),
    ]
